sudo: false
language: node_js
node_js:
  - '5'
  - '4'
  - '0.10'
before_install:
  - gem update --system
  - gem install compass
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
